### ISSUE TITLE
New plot: volcanos

### ISSUE THREAD

**Issue by dadosdelaplace** [jbengler/tidyplots#9]
Hi!

Thanks for the package, it is amazing!

I wonder if it is possible to include some volcano plots (since it is a very common plot in bioinformatics). I can help with us if u want

thanks!

**Comment by jbengler** [comment]
Hi @dadosdelaplace 

Thank you for your interest in tidyplots and for offering to help—I really appreciate it!

I completely agree that volcano plots are a valuable tool in bioinformatics. In tidyplots, they could likely be created using a combination of `add_data_points()` and `add_data_labels()`. I’d be very eager to see your version of a volcano plot built with tidyplots!

If you meant that tidyplots should include a dedicated function specifically for volcano plots, I’d currently lean against it. I envision tidyplots as more of a modular system, focusing on flexibility rather than specialized functions for specific use cases.

Best regards,
Jan

**Comment by sorenhejgaard** [comment]
Hi Jan,

The use-cases page is excellent - thank you so much for sharing!

I have a small request: is it possible to make 95% confidence interval elipses around each group on top of the scatterplot?

Best
Søren

**Comment by jbengler** [comment]
Hi Søren,

you probably want to add the ellipses to the PCA plot, right?

```
library(tidyverse)
library(tidyplots)

df <- 
  read_csv("https://tidyplots.org/data/pca-plot.csv")

df %>% 
  tidyplot(x = pc1, y = pc2, color = group) %>% 
  add_data_points(size = 1.3, white_border = TRUE) %>% 
  adjust_x_axis_title(paste0("Component 1 (", format_number(df$pc1_var*100), "%)")) %>% 
  adjust_y_axis_title(paste0("Component 2 (", format_number(df$pc2_var*100), "%)")) %>% 
adjust_colors(colors_discrete_apple) %>% 
  adjust_legend_title("Group") %>% 
  add(stat_ellipse(level = 0.95, alpha = 0.3))
```

Best
Jan

**Comment by sorenhejgaard** [comment]
Hi Jan

Thank you so much, Jan 😊

Best
Søren

Fra: Jan Broder Engler ***@***.***>
Sendt: 14. januar 2025 11:00
Til: jbengler/tidyplots ***@***.***>
Cc: sorenhejgaard ***@***.***>; Comment ***@***.***>
Emne: Re: [jbengler/tidyplots] New plot: volcanos (Issue #9)


Hi Søren,

you probably want to add the ellipses to the PCA plot, right?

library(tidyverse)

library(tidyplots)



df <-

  read_csv("https://tidyplots.org/data/pca-plot.csv")



df %>%

  tidyplot(x = pc1, y = pc2, color = group) %>%

  add_data_points(size = 1.3, white_border = TRUE) %>%

  adjust_x_axis_title(paste0("Component 1 (", format_number(df$pc1_var*100), "%)")) %>%

  adjust_y_axis_title(paste0("Component 2 (", format_number(df$pc2_var*100), "%)")) %>%

adjust_colors(colors_discrete_apple) %>%

  adjust_legend_title("Group") %>%

  add(stat_ellipse(level = 0.95, alpha = 0.3))

Best
Jan

**Comment by jbengler** [comment]
You are welcome!
